### ISSUE TITLE
can the program used for predict many sequence to one protein?  

### ISSUE THREAD

**Issue by Xiongb-lab** [RoniGurvich/Peptriever#19]
Thanks for providing this good program to predict the protein and peptide interaction.  I am current doing a peptide phagy display experiment. And I am wondering is this program can be used for predict which peptide has potential to bind to the target protein? I have thousands of possible peptides needs to assess. If this program can, could you tell me how to do this in command line? Thanks so much!

**Comment by RoniGurvich** [comment]
You can update the sample python code at [huggingface](https://huggingface.co/ronig/protein_biencoder) to perform the task you are describing
